### PR TITLE
Add new vignette Download Expression Matrix for Scanpy

### PR DESCRIPTION
**Pull request by jnkrupp**
Add a vignette, "Download Expression Matrix for Scanpy" which shows the user how to get a `.results` file, take the necessary values from it, and from them create a `.mtx` file, whose data can then be used in scanpy. This vignette completes "Download SmartSeq2 expression matrix as an input to scanpy" in the README.

### CODE REVIEW

**Comment by jnkrupp** [comment]
My guesses at things that need fixing:
* The efficiency of some of the code, namely the printing and csv reading/writing
* Possibly some of the comments and wording

**Comment by mckinsel** [comment]
Hey thanks @jnkrupp ! I have a few comments/questions for you:

- Can you add a little more description of `match` behavior in ES? Like in plain language, what is that query looking for?
- Telling a user to restart their computer is a touch heavy-handed. I think you can do something like `client.host = 'https://dss.integration.data.humancellatlas.org/v1'` and not have to worry about editing the config.json
- More generally, do we want to include instructions on how to switch to the integration DSS? That's something we would really never want a user to do. I'm not sure what the right answer is here.
- There's a magic 28 in there. Is that just supposed to mean "select any record'?
- The `file` variable redefines a builtin. Can you change the variable name?
- The "mtx" extension usually refers to the [matrix market format](https://math.nist.gov/MatrixMarket/formats.html). You can write that if you want using `scipy.io.mmwrite`, or you can change the extension to "tsv", which is what you have.
- 58,347 seems like a lot of genes. Are you sure that's right?
- I think you have the transpose of the matrix loaded into scanpy. It shows 58,347 cells and one gene.
- What would you think of loading data from two SS2 bundles into scanpy? Not sure how much more work that would be and it isn't totally necessary, but it could be nice to show more than one cell being loaded into scanpy.

**Comment by jnkrupp** [comment]
Thanks for the feedback @mckinsel ! I've finished making the changes now.
> Can you add a little more description of match behavior in ES? Like in plain language, what is that query looking for?
More details have been added on how the query works.
> Telling a user to restart their computer is a touch heavy-handed. I think you can do something like client.host = 'https://dss.integration.data.humancellatlas.org/v1' and not have to worry about editing the config.json
> More generally, do we want to include instructions on how to switch to the integration DSS? That's something we would really never want a user to do. I'm not sure what the right answer is here.
I asked Kevin, and he said he thought it'd be best if we included directions on how to switch to the integration DSS, but then removed them after the release. My plan is to create an issue for this after this PR is merged. Also, I've followed your advice with `client.host`.
> There's a magic 28 in there. Is that just supposed to mean "select any record'?
> The file variable redefines a builtin. Can you change the variable name?
> The "mtx" extension usually refers to the matrix market format. You can write that if you want using scipy.io.mmwrite, or you can change the extension to "tsv", which is what you have.
> 58,347 seems like a lot of genes. Are you sure that's right?
> I think you have the transpose of the matrix loaded into scanpy. It shows 58,347 cells and one gene.
All of these have now been fixed, leaving file type as .tsv and transposing the AnnData object.
> What would you think of loading data from two SS2 bundles into scanpy? Not sure how much more work that would be and it isn't totally necessary, but it could be nice to show more than one cell being loaded into scanpy.
This has been changed as well. Both the bundles have the same data, but that shouldn't be a problem.

**Comment by mckinsel** [comment]
Hey thanks @jnkrupp , I'm going to merge. (And apologies for the shameful delay!)

**Pull request merged**
